name = "JuliaPythonAdaptor"
uuid = "0e307d70-50ba-423d-98c4-b9d407ed9420"
authors = ["thautwarm <twshere@outlook.com> and contributors"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
julia = "1.3"
PythonCall = "0.9.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
